### ISSUE TITLE
Sometimes GALX goes missing

### ISSUE THREAD

**Issue by nonspecialist** [cevoaustralia/aws-google-auth#1]
Sometimes, it seems that Google doesn't emit a GALX cookie or hidden value in the initial page returned from hitting the SSO signin url. This breaks `keyme`, because it assumes that the value is always there.

It's not yet clear whether this is something google does randomly, or in response to certain circumstances, or whether I've accidentally stumbled on a coincidental change in behaviour, but the tool shouldn't crash with a nasty stack trace in any case:

```python
Traceback (most recent call last):
  File "/usr/bin/aws-google-auth", line 11, in <module>
    load_entry_point('aws-google-auth==0.0.1', 'console_scripts', 'aws-google-auth')()
  File "/usr/lib/python2.7/site-packages/aws_google_auth/aws_google_auth.py", line 70, in main
    google.session = google.login_to_google()
  File "/usr/lib/python2.7/site-packages/keyme/__init__.py", line 74, in login_to_google
    galx = decoded.find('input', {'name': 'GALX'}).get('value')
AttributeError: 'NoneType' object has no attribute 'get'

```

**Comment by nonspecialist** [comment]
Resolved with the recent rewrite; if GALX is provided, it will be used, otherwise it'll be ignored.
