### ISSUE TITLE
save-failure-html always gives TypeError 

### ISSUE THREAD

**Issue by max-rocket-internet** [cevoaustralia/aws-google-auth#122]
I always get this when trying to use the `--save-failure-html` argument:

```
$ aws-google-auth --role-arn arn:aws:iam::666666666:role/sso/sso-xxxxxxxx --duration 43200 --profile xx-xxxx --keyring --save-failure-html
Failed to import U2F libraries, U2F login unavailable. Other methods can still continue.
Open the Google App, and tap 'Yes' on the prompt to sign in ...
SAML lookup failed, storing failure page to 'saml.html' to assist with debugging.
Traceback (most recent call last):
  File "/Users/max.williams/Library/Python/3.6/lib/python/site-packages/aws_google_auth/google.py", line 284, in parse_saml
    saml_element = parsed.find('input', {'name': 'SAMLResponse'}).get('value')
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/max.williams/Library/Python/3.6/bin/aws-google-auth", line 11, in <module>
    sys.exit(main())
  File "/Users/max.williams/Library/Python/3.6/lib/python/site-packages/aws_google_auth/__init__.py", line 232, in main
    cli(cli_args)
  File "/Users/max.williams/Library/Python/3.6/lib/python/site-packages/aws_google_auth/__init__.py", line 66, in cli
    process_auth(args, config)
  File "/Users/max.williams/Library/Python/3.6/lib/python/site-packages/aws_google_auth/__init__.py", line 192, in process_auth
    saml_xml = google_client.parse_saml()
  File "/Users/max.williams/Library/Python/3.6/lib/python/site-packages/aws_google_auth/google.py", line 290, in parse_saml
    out.write(self.session_state.text.encode('utf-8'))
TypeError: write() argument must be str, not bytes
```

**Comment by stevemac007** [comment]
Grrrr - going to guess this is another python 3 vs python 2 issue - let me see if I can add some test coverage for this one to reproduce it and squash it.

**Comment by max-rocket-internet** [comment]
Or just don't support both versions? Just aim for 3 😎

**Comment by max-rocket-internet** [comment]
OK I edited `aws_google_auth/google.py` to capture the output HTML and it looks like this:

<img width="433" alt="screen shot 2019-02-06 at 12 05 18" src="https://user-images.githubusercontent.com/8859277/52337342-a69dae00-2a07-11e9-93b5-8fad51d4dc9b.png">

**Comment by max-rocket-internet** [comment]
There was no delay though. Run command and click `yes` in the Google app within 1 second.

**Comment by stevemac007** [comment]
Just pushed `test_saml_parse` to protect against this issue.

**Comment by max-rocket-internet** [comment]
OK thanks Steve! The problem seems to happen much less for me these days but I'll use this branch next time.

**Comment by stevemac007** [comment]
Merging the fix to master - it looks like it was a defect with python3 and the save flag fix.

**Comment by max-rocket-internet** [comment]
This was fixed. Thanks @stevemac007!
