### ISSUE TITLE
Can not find any timezone information

### ISSUE THREAD

**Issue by pauldraper** [cevoaustralia/aws-google-auth#133]
```
Open the Google App, and tap 'Yes' on the prompt to sign in ...
Assuming arn:aws:iam::898262571791:role/admin
ERROR:root:'Can not find any timezone configuration'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aws_google_auth/__init__.py", line 72, in cli
    process_auth(args, config)
  File "/usr/local/lib/python3.6/dist-packages/aws_google_auth/__init__.py", line 243, in process_auth
    print("Credentials Expiration: " + format(amazon_client.expiration.astimezone(get_localzone())))
  File "/usr/local/lib/python3.6/dist-packages/tzlocal/unix.py", line 131, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/local/lib/python3.6/dist-packages/tzlocal/unix.py", line 125, in _get_localzone
    raise pytz.UnknownTimeZoneError('Can not find any timezone configuration')
pytz.exceptions.UnknownTimeZoneError: 'Can not find any timezone configuration'
```

**Comment by pauldraper** [comment]
I had to ```apt install tzdata``` and choose one of the timezones.
