### ISSUE TITLE
--help broken in 0.0.8 (Python 3 support)

### ISSUE THREAD

**Issue by SamBarker** [cevoaustralia/aws-google-auth#14]
Minor grumble, just installed the 0.0.8 release with pip3 and running `aws-google-auth --help`

breaks with:

```
$ aws-google-auth --help
Traceback (most recent call last):
  File "/usr/local/bin/aws-google-auth", line 11, in <module>
    load_entry_point('aws-google-auth==0.0.8', 'console_scripts', 'aws-google-auth')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/aws_google_auth/__init__.py", line 55
    print "WARNING: Clamping duration_seconds to 3600"
                                                     ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by stevemac007** [comment]
Thanks for picking this up...  Looks like a python 2.X vs 3.X issue.

**Comment by SamBarker** [comment]
Oh, is python3 not supported?

**Comment by stevemac007** [comment]
It should be, we probably have not tested against it fully. I'll try and get a look at validating that assumption tonight.

**Comment by nonspecialist** [comment]
It's not explicitly supported, yet -- though we should support it, yes. The package description doesn't mention Python 3, so I'm a teensy bit surprised that `pip3` installed it

**Comment by SamBarker** [comment]
Sorry, been a long time since I did much with python, just picked latest for this on my work machine.

I've got python 2.7 at home and --help from 0.0.8 works fine.

**Comment by nonspecialist** [comment]
no problem -- we should support both!

**Comment by nonspecialist** [comment]
Should be fixed by the above merge. Thanks for reporting it!
