### ISSUE TITLE
Password manager + CAPTCHA

### ISSUE THREAD

**Issue by jtatum** [cevoaustralia/aws-google-auth#140]
The README mentions that the Google password can be supplied via stdin, for use with password managers. This seems to work, but when I try it, I can't answer the CAPTCHA prompt. The output below happens immediately without any input from me:
```
$ echo password-test | aws-google-auth
Google Password:
Please visit the following URL to view your CAPTCHA: https://accounts.google.com/Captcha?v=2&ctoken=<token>
ERROR:root:EOF when reading a line
Traceback (most recent call last):
  File "/Users/jtatum/projects/aws-google-auth/aws_google_auth/__init__.py", line 72, in cli
    process_auth(args, config)
  File "/Users/jtatum/projects/aws-google-auth/aws_google_auth/__init__.py", line 212, in process_auth
    google_client.do_login()
  File "/Users/jtatum/projects/aws-google-auth/aws_google_auth/google.py", line 260, in do_login
    sess = self.handle_captcha(sess, payload)
  File "/Users/jtatum/projects/aws-google-auth/aws_google_auth/google.py", line 381, in handle_captcha
    captcha_input = raw_input("Captcha (case insensitive): ") or None
EOFError: EOF when reading a line
Captcha (case insensitive): $
```

**Comment by stevemac007** [comment]
This feels like a challenge with the whole redirection approach.
I personally don't use the password injection like this, prefer to use the keyring integration for password management.

Suggestions are welcome for an approach to make this more resilient to the CAPTCHA requirement.

**Comment by ccmattr** [comment]
In case it helps, this is the script I use I'm currently managing my login:
```
#!/usr/bin/expect -f

# spawn aws-google-auth --save-failure-html -a -d $dur
# spawn aws-google-auth --save-failure-html --auto-duration -l debug
spawn aws-google-auth --save-failure-html --auto-duration

# exp_internal 1

expect {
  "Google Password:" {
    # interact -o "\n" exp_continue
    set pw [exec op get item --fields password [op]
    send "$pw\r"

    expect {
      "Please visit the following URL to view your CAPTCHA:" {
        # interact -o "\n" exp_continue
        expect_user -timeout 3600 -re "(.*)\[\r\n]"
        send "$expect_out(1,string)\r"
        
        expect "Enter MFA choice number" {
          send "1\r"
        }
      }

      "Enter MFA choice number" {
        send "1\r"
      }
    }

    expect "MFA token:" {
      set mfa [exec op get totp [id]
      send "$mfa\r"
    }
  }
  "Credentials Expiration:"
}

expect eof
```
