### ISSUE TITLE
Cannot authenticate with Google, won't redirect to challenge page

### ISSUE THREAD

**Issue by james-welly** [cevoaustralia/aws-google-auth#184]
Have been using the docker image with this repo to authenticate with Google for some time. As of yesterday it stopped working with the following error message:

```Google Password:
ERROR:root:'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/build/aws_google_auth/__init__.py", line 78, in cli
    process_auth(args, config)
  File "/build/aws_google_auth/__init__.py", line 242, in process_auth
    google_client.do_login()
  File "/build/aws_google_auth/google.py", line 235, in do_login
    passwd_challenge_url = 'https://accounts.google.com' + form.get('action')
AttributeError: 'NoneType' object has no attribute 'get'
```

I have removed the image and downloaded the latest version and still get the error. I have also created a virtual environment with the latest python packages and run the following command and still no joy.

```
aws-google-auth -k -p ${AWS_PROFILE_NAME} -I ${GOOGLE_IDP_ID} -S ${GOOGLE_SP_ID} -R ${AWS_DEFAULT_REGION} --resolve-aliases -q
```

I have exported the challenge page to html (attached). Everyone else in my organisation is still able to use the repo to authenticate. Any thoughts?

[out2.html.zip](https://github.com/cevoaustralia/aws-google-auth/files/4508908/out2.html.zip)

**Comment by dgcgh** [comment]
I'm seeing a  similar error that looks like this:
`ERROR:root:'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/davidgcheney/.local/lib/python3.7/site-packages/aws_google_auth/__init__.py", line 76, in cli
    process_auth(args, config)
  File "/home/davidgcheney/.local/lib/python3.7/site-packages/aws_google_auth/__init__.py", line 233, in process_auth
    google_client.do_login()
  File "/home/davidgcheney/.local/lib/python3.7/site-packages/aws_google_auth/google.py", line 238, in do_login
    passwd_challenge_url = 'https://accounts.google.com' + form.get('action')
AttributeError: 'NoneType' object has no attribute 'get'
`
![Screenshot 2020-04-22 at 12 53 55](https://user-images.githubusercontent.com/967100/80028287-bfbe3d80-8499-11ea-90f5-8385eab12fc8.png)

**Comment by Zlender** [comment]
I'm seeing same error
```
ERROR:root:'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-google-auth/0.0.35/libexec/lib/python3.8/site-packages/aws_google_auth/__init__.py", line 76, in cli
    process_auth(args, config)
  File "/usr/local/Cellar/aws-google-auth/0.0.35/libexec/lib/python3.8/site-packages/aws_google_auth/__init__.py", line 233, in process_auth
    google_client.do_login()
  File "/usr/local/Cellar/aws-google-auth/0.0.35/libexec/lib/python3.8/site-packages/aws_google_auth/google.py", line 235, in do_login
    passwd_challenge_url = 'https://accounts.google.com' + form.get('action')
AttributeError: 'NoneType' object has no attribute 'get'
```

I can't seem to find a way around it.

**Comment by tlvince** [comment]
Duplicate of #179

**Comment by stevemac007** [comment]
Is this resolved with the latest build `0.0.36` which has the fixed for captcha.  

Please let us know if this resolves your issue.

**Comment by williamcoates** [comment]
My whole team is getting this error with `0.0.36`
<img width="476" alt="Screenshot 2020-09-16 at 10 35 59" src="https://user-images.githubusercontent.com/50446/93320157-a0d59480-f808-11ea-98a5-11c23a2d93fe.png">

**Comment by Frietziek** [comment]
Hello, I'm getting the same problem @james-welly. Do you find any solution to it?

**Comment by Frietziek** [comment]
Not sure if it helps someone, but in my case, the problem seem to be that at my company we are using something called MobileIron as second factor authentication with our smarthphone, and when aws-google-atuh code is doing this:

```python
# POST to account login info page, to collect profile and session info
        sess = self.post(account_login_url, data=payload)
```

Its gets this html:
![image](https://user-images.githubusercontent.com/10697457/97110960-cd5bb680-16ba-11eb-9ce7-129461eb3ffe.png)

Which doesn't have the following expected form:

```python
form = challenge_page.find('form', {'id': 'challenge'})
            passwd_challenge_url = 'https://accounts.google.com' + form.get('action')
```

So it breaks:

```python
ERROR:root:'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aws_google_auth/__init__.py", line 78, in cli
    process_auth(args, config)
  File "/usr/local/lib/python3.8/dist-packages/aws_google_auth/__init__.py", line 242, in process_auth
    google_client.do_login()
  File "/usr/local/lib/python3.8/dist-packages/aws_google_auth/google.py", line 235, in do_login
    passwd_challenge_url = 'https://accounts.google.com' + form.get('action')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by rama3319** [comment]
My whole team started getting below error with aws-google-auth
<img width="914" alt="image" src="https://user-images.githubusercontent.com/25374772/165350595-1f369687-faa2-411e-a585-fa1e30e5edce.png">

**Comment by rmirandarj** [comment]
> My whole team started getting below error with aws-google-auth. We tried resetting cookies, uninstalled & installed aws-google-auth but did not help. Can some please shed some light on it. It was working fine until yesterday. <img alt="image" width="914" src="https://user-images.githubusercontent.com/25374772/165350595-1f369687-faa2-411e-a585-fa1e30e5edce.png">

I was getting the same problem, but I just added this flag `--bg-response js_enabled`, running the latest version of aws-google-auth (0.0.38).

`aws-google-auth --bg-response js_enabled`
