### ISSUE TITLE
Invalid username or password

### ISSUE THREAD

**Issue by mandeep-bal** [cevoaustralia/aws-google-auth#187]
Hey,

I have been trying to access the AWS CLI by following the instructions but still getting the errors - Invalid username or password.

So far i have tried on Windows, linux OS, Changed the password and tried, local installation and docker  installation.

Google Authenticator is enabled however haven't even received the notification.

Debug Logs - DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): accounts.google.com:443
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "GET /o/saml2/initsso?idpid=C03mxsvfp&spid=153221826964&forceauthn=false HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "GET /ServiceLogin?passive=1209600&continue=https://accounts.google.com/o/saml2/initsso?idpid%3DC03mxsvfp%26spid%3D153221826964%26forceauthn%3Dfalse%26from_login%3D1%26as%3DD5MbpRKiofP9YYrjCUYK4w&followup=https://accounts.google.com/o/saml2/initsso?idpid%3DC03mxsvfp%26spid%3D153221826964%26forceauthn%3Dfalse%26from_login%3D1%26as%3DD5MbpRKiofP9YYrjCUYK4w&ltmpl=popup&oauth=1&faa=1&sarp=1&scc=1 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "POST /signin/v1/lookup HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "POST /signin/v1/lookup HTTP/1.1" 200 None

**Comment by Rukaan** [comment]
I tried this one and it works for me, hope it might solve yours too

https://github.com/cevoaustralia/aws-google-auth/issues/179#issuecomment-616475122

**Comment by mandeep-bal** [comment]
I checked that one. Feels like this one is different. Here is the response
along with HTML output. Can you please guide me with further steps.

--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/urllib3/connection.py", line 157,
in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/lib/python3.5/site-packages/urllib3/util/connection.py", line
61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line
672, in urlopen
    chunked=chunked,
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line
376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line
994, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.5/site-packages/urllib3/connection.py", line 300,
in connect
    conn = self._new_conn()
  File "/usr/lib/python3.5/site-packages/urllib3/connection.py", line 169,
in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError:
<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9fc25b33c8>:
Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/requests/adapters.py", line 449,
in send
    timeout=timeout
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line
720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/lib/python3.5/site-packages/urllib3/util/retry.py", line 436,
in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='
accounts.google.com', port=443): Max retries exceeded with url:
/o/saml2/initsso?idpid=C03mxsvfp&spid=153221826964&forceauthn=false (Caused
by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object
at 0x7f9fc25b33c8>: Failed to establish a new connection: [Errno -3] Try
again',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/aws_google_auth/google.py", line 111, in get
    response = self.check_for_failure(self.session.get(url))
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 543,
in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 530,
in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 643,
in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.5/site-packages/requests/adapters.py", line 516,
in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='
accounts.google.com', port=443): Max retries exceeded with url:
/o/saml2/initsso?idpid=C03mxsvfp&spid=153221826964&forceauthn=false (Caused
by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object
at 0x7f9fc25b33c8>: Failed to establish a new connection: [Errno -3] Try
again',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 986, in emit
    msg = self.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 836, in format
    return fmt.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 573, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.5/logging/__init__.py", line 336, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/bin/aws-google-auth", line 11, in <module>
    load_entry_point('aws-google-auth', 'console_scripts',
'aws-google-auth')()
  File "/build/aws_google_auth/__init__.py", line 289, in main
    cli(cli_args)
  File "/build/aws_google_auth/__init__.py", line 78, in cli
    process_auth(args, config)
  File "/build/aws_google_auth/__init__.py", line 242, in process_auth
    google_client.do_login()
  File "/build/aws_google_auth/google.py", line 175, in do_login
    sess = self.get(self.login_url)
  File "/build/aws_google_auth/google.py", line 114, in get
    'There was a connection error, check your network settings.', e)
Message: 'There was a connection error, check your network settings.'
Arguments: (ConnectionError(MaxRetryError("HTTPSConnectionPool(host='
accounts.google.com', port=443): Max retries exceeded with url:
/o/saml2/initsso?idpid=C03mxsvfp&spid=153221826964&forceauthn=false (Caused
by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object
at 0x7f9fc25b33c8>: Failed to establish a new connection: [Errno -3] Try
again',))",),),)

**Comment by mandeep-bal** [comment]
Thanks, it worked using https://github.com/brunodasilvalenga/aws-google-auth.git
