### ISSUE TITLE
Error: MFA method selection fails with list index out of range

### ISSUE THREAD

**Issue by bhang** [cevoaustralia/aws-google-auth#234]
**Error details**
```
❯ aws-google-auth
Google Password:
/signin/challenge/ootp/4 --> *
/signin/challenge/bc/3 --> *
Choose MFA method from available:
Enter MFA choice number (1): 1
ERROR:root:list index out of range
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-google-auth/0.0.37_3/libexec/lib/python3.9/site-packages/aws_google_auth/__init__.py", line 79, in cli
    process_auth(args, config)
  File "/usr/local/Cellar/aws-google-auth/0.0.37_3/libexec/lib/python3.9/site-packages/aws_google_auth/__init__.py", line 243, in process_auth
    google_client.do_login()
  File "/usr/local/Cellar/aws-google-auth/0.0.37_3/libexec/lib/python3.9/site-packages/aws_google_auth/google.py", line 311, in do_login
    sess = self.handle_selectchallenge(sess)
  File "/usr/local/Cellar/aws-google-auth/0.0.37_3/libexec/lib/python3.9/site-packages/aws_google_auth/google.py", line 854, in handle_selectchallenge
    challenge_id = challenges[selected_challenge][1]
IndexError: list index out of range
```

The lines marked with an `*` are coming from a `print()` I added to see what the challenge options were. Neither of those match the `if/elif` block so the challenges list ends up being empty. Perhaps Google changed something again on their end ?

Also the MFA method selection seems new - previously it used to directly go to the "Check your phone..." step

**Comment by bhang** [comment]
**Update:** This may have been a transient Google thing. It's back to working for me.

**Comment by p-hash** [comment]
I have the same issue
