### ISSUE TITLE
throwing this error after entering password

### ISSUE THREAD

**Issue by jahir575bizcloudexperts** [cevoaustralia/aws-google-auth#256]
```
ERROR:root:'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\aws_google_auth\__init__.py", line 79, in cli
    process_auth(args, config)
  File "C:\Python\lib\site-packages\aws_google_auth\__init__.py", line 243, in process_auth
    google_client.do_login()
  File "C:\Python\lib\site-packages\aws_google_auth\google.py", line 256, in do_login
    passwd_challenge_url = 'https://accounts.google.com/' + form.get('action')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by guisilva-cid** [comment]
https://github.com/cevoaustralia/aws-google-auth/issues/253#issuecomment-1110957990

**Comment by stevemac007** [comment]
Google looks to have made changes to the responses, a fix for this should be available in release https://github.com/cevoaustralia/aws-google-auth/releases/tag/0.0.38
