### ISSUE TITLE
response signature invalid (u2f)

### ISSUE THREAD

**Issue by GingaNinja** [cevoaustralia/aws-google-auth#270]
This has been working fine and then it stopped working this morning. I'm not aware that I have done anything different, but I'm now getting the following error when running the command `aws-google-auth -k -p ___ -r arn:aws:iam::___:role/___ --bg-response js_enabled`:

```bash
ERROR:root:An error occurred (InvalidIdentityToken) when calling the AssumeRoleWithSAML operation: Response signature invalid
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/aws_google_auth/__init__.py", line 79, in cli
    process_auth(args, config)
  File "/opt/homebrew/lib/python3.10/site-packages/aws_google_auth/__init__.py", line 279, in process_auth
    print("Credentials Expiration: " + format(amazon_client.expiration.astimezone(get_localzone())))
  File "/opt/homebrew/lib/python3.10/site-packages/aws_google_auth/amazon.py", line 64, in expiration
    return self.token['Credentials']['Expiration']
  File "/opt/homebrew/lib/python3.10/site-packages/aws_google_auth/amazon.py", line 44, in token
    self.__token = self.assume_role(self.config.role_arn,
  File "/opt/homebrew/lib/python3.10/site-packages/aws_google_auth/amazon.py", line 117, in assume_role
    res = self.sts_client.assume_role_with_saml(**sts_call_vars)
  File "/opt/homebrew/lib/python3.10/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/botocore/client.py", line 934, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidIdentityTokenException: An error occurred (InvalidIdentityToken) when calling the AssumeRoleWithSAML operation: Response signature invalid
Assuming arn:aws:iam::___:role/___
```

**Comment by kriation** [comment]
Your SAML certificate has expired.
https://docs.aws.amazon.com/IAM/latest/UserGuide/troubleshoot_saml.html#troubleshoot_saml_invalid-metadata

**Comment by GingaNinja** [comment]
ah thanks for that. It looks like that was indeed the problem!

**Comment by kriation** [comment]
Happy to help! Can you close this issue?
