### ISSUE TITLE
python2 broken on reading existing config

### ISSUE THREAD

**Issue by nonspecialist** [cevoaustralia/aws-google-auth#50]
When using python2.7 for 0.0.19, I get:

```
me@tak.local ~ $ aws-google-auth -a --resolve-aliases 
Failed to import U2F libraries, U2F login unavailable. Other methods can still continue.
Traceback (most recent call last):
  File "/usr/bin/aws-google-auth", line 11, in <module>
    load_entry_point('aws-google-auth==0.0.19', 'console_scripts', 'aws-google-auth')()
  File "/usr/lib/python2.7/site-packages/aws_google_auth/__init__.py", line 54, in main
    cli(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/aws_google_auth/__init__.py", line 79, in cli
    config.read(config.profile)
  File "/usr/lib/python2.7/site-packages/aws_google_auth/configuration.py", line 182, in read
    read_ask_role = config_parser[profile_string].getboolean('google_config.ask_role', None)
AttributeError: RawConfigParser instance has no attribute '__getitem__'
```

because the python3 syntax for `RawConfigParser` to get a whole section via `config_parser['section name']` is not available in the native python2.7 `configparser`

A version-independent syntax would be `config_parser.getboolean(profile_string, item)` or `config_parser.getint(profile_string, item)`

**Comment by nonspecialist** [comment]
fixed by PR #51
