### ISSUE TITLE
"SyntaxError: unexpected EOF while parsing" using security key

### ISSUE THREAD

**Issue by tjbaker** [cevoaustralia/aws-google-auth#53]
I got the following exception after inserting my key and pressing enter.

```
No U2F device found. 5 attempts remaining.
Insert your U2F device and press enter to try again...
Traceback (most recent call last):
  File "/usr/local/bin/aws-google-auth", line 11, in <module>
    load_entry_point('aws-google-auth==0.0.18', 'console_scripts', 'aws-google-auth')()
  File "/Library/Python/2.7/site-packages/aws_google_auth/__init__.py", line 53, in main
    cli(sys.argv[1:])
  File "/Library/Python/2.7/site-packages/aws_google_auth/__init__.py", line 152, in cli
    google_client.do_login()
  File "/Library/Python/2.7/site-packages/aws_google_auth/google.py", line 138, in do_login
    sess = self.handle_sk(sess)
  File "/Library/Python/2.7/site-packages/aws_google_auth/google.py", line 184, in handle_sk
    input("Insert your U2F device and press enter to try again...")
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
```

**Comment by nonspecialist** [comment]
Under Python 3, this returns whatever string is typed; with Python 2, this is equivalent to `eval(raw_input(prompt))` and so attempts to execute whatever the user types.

**Comment by alex4108** [comment]
Similar issue here

Using Python 3.6.8 in Ubuntu 18.04 LTS (Windows Subsystem For Linux v2 Environment!)
U2F security key enabled on my google account
Post-password prompt:
Google Password:
ERROR:root:Was unable to find appid value in googles SAML page
Traceback (most recent call last):
  File "/home/alex/.local/lib/python3.6/site-packages/aws_google_auth/google.py", line 165, in find_app_id
    searchResult = re.search('"appid":"[a-z://.-_]+"', inputString).group()
AttributeError: 'NoneType' object has no attribute 'group'

Once U2F is disabled on my google account, I'm able to 2FA using SMS or Push notification
