### ISSUE TITLE
Create credentials either relative to AWS_CONFIG_FILE (if not null) or use another variable AWS_CREDENTIALS_FILE

### ISSUE THREAD

**Issue by rverma-nikiai** [cevoaustralia/aws-google-auth#75]
Create credentials either relative to AWS_CONFIG_FILE (if not null) or use another variable AWS_CREDENTIALS_FILE to provide the location of credentials files.

https://docs.aws.amazon.com/cli/latest/userguide/cli-config-files.html

Getting exception: 

```
 aws-google-auth -D --no-cache  -d 3400 -p default
Failed to import U2F libraries, U2F login unavailable. Other methods can still continue.
Google username: rohit.verma@niki.ai
Google Password: 
Open the Google App, and tap 'Yes' on the prompt to sign in ...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/aws_google_auth/amazon.py", line 75, in resolve_aws_alias
    saml = self.sts_client.assume_role_with_saml(RoleArn=role,
  File "/usr/lib/python2.7/site-packages/aws_google_auth/amazon.py", line 20, in sts_client
    return boto3.client('sts', region_name=self.config.region)
  File "/usr/lib/python2.7/site-packages/boto3/__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 828, in create_client
    verify = self.get_config_variable('ca_bundle')
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 279, in get_config_variable
    elif self._found_in_config_file(methods, var_config):
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 306, in _found_in_config_file
    return var_config[0] in self.get_scoped_config()
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 383, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
ProfileNotFound: The config profile (default) could not be found
```

**Comment by dgilbert82** [comment]
You should be able to use the `AWS_SHARED_CREDENTIALS_FILE` to point to the filename you want to use for the credentials filename.  See botocore/session.py

https://github.com/boto/botocore/blob/9ad8c0d8b9d9c5fa3aebbf15e8a581e40a909d3a/botocore/session.py#L90
