### ISSUE TITLE
Random errors: AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by max-rocket-internet** [cevoaustralia/aws-google-auth#90]
```
Open the Google App, and tap 'Yes' on the prompt to sign in ...
Traceback (most recent call last):
  File "/Users/max.williams/Library/Python/3.6/lib/python/site-packages/aws_google_auth/google.py", line 259, in parse_saml
    'name': 'SAMLResponse'
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/aws-google-auth", line 11, in <module>
    sys.exit(main())
  File "/Users/max.williams/Library/Python/3.6/lib/python/site-packages/aws_google_auth/__init__.py", line 226, in main
    cli(cli_args)
  File "/Users/max.williams/Library/Python/3.6/lib/python/site-packages/aws_google_auth/__init__.py", line 65, in cli
    process_auth(args, config)
  File "/Users/max.williams/Library/Python/3.6/lib/python/site-packages/aws_google_auth/__init__.py", line 187, in process_auth
    saml_xml = google_client.parse_saml()
  File "/Users/max.williams/Library/Python/3.6/lib/python/site-packages/aws_google_auth/google.py", line 263, in parse_saml
    'Could not find SAML response, check your credentials')
RuntimeError: Could not find SAML response, check your credentials
```

Any idea?

**Comment by stevemac007** [comment]
I believe this happens when you are too slow to click yes, I get this too and started working on debugging it recently.

**Comment by max-rocket-internet** [comment]
Too slow? It was about 2 seconds at most.

**Comment by stevemac007** [comment]
I see this when I am too slow, but there may very well be other reasons this occurs.
I'm looking at adding some sort of option to dump the HTML for better debugging.

This whole library has been reverse engineered from the pages as there is no documented API for the google auth workflow - they may have changed things too.

**Comment by max-rocket-internet** [comment]
Great, sounds like a good idea, Steve.

**Comment by stevemac007** [comment]
MR #94 is the first crack at helping with this. 

I've just released `0.0.27` and will continue to look at #94 to see if it covers the right scenarios.

**Comment by max-rocket-internet** [comment]
OK so I wait for that PR to be merged and a new release and then I'll update this issue with the output.

**Comment by max-rocket-internet** [comment]
Nope, all good. Thanks Steve!
