### ISSUE TITLE
default when only one role to assume

### ISSUE THREAD

**Issue by rafilkmp3** [cevoaustralia/aws-google-auth#93]
hi, when we have only one role to assume the following dialog is prompt. if i press a simple enter without choose 1   I face this error:

Type the number (1 - 1) of the role to assume: 

>   Traceback (most recent call last):
>   File "/usr/local/bin/aws-google-auth", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python2.7/site-packages/aws_google_auth/__init__.py", line 226, in main
>     cli(cli_args)
>   File "/usr/local/lib/python2.7/site-packages/aws_google_auth/__init__.py", line 65, in cli
>     process_auth(args, config)
>   File "/usr/local/lib/python2.7/site-packages/aws_google_auth/__init__.py", line 213, in process_auth
>     config.role_arn, config.provider = util.Util.pick_a_role(roles)
>   File "/usr/local/lib/python2.7/site-packages/aws_google_auth/util.py", line 53, in pick_a_role
>     return list(roles.items())[int(choice) - 1]
> ValueError: invalid literal for int() with base 10: 'Type the number (1 - 1) of the role to assume:'

**Comment by mide** [comment]
This could likely be added as a small `if` at the top of the `pick_a_role()` function.
https://github.com/cevoaustralia/aws-google-auth/blob/91cb4f764655082631b61d8c1ba07742dbe9f6f0/aws_google_auth/util.py#L18-L19

I think it can be something really simple, like the following. I don't have the time right now to test/make a PR, but this is a start.

```python
if len(roles) == 1:
    return roles[0]
```
