### ISSUE TITLE
macOS 10.13.6 and -k yields error:

### ISSUE THREAD

**Issue by sinkr** [cevoaustralia/aws-google-auth#99]
HomeBrew-installed Python 2.7.15.

Bottom-line error: AssertionError: Expected password to be a string. Got <type 'unicode'>.

(I am entering the correct password for KeyChain access, etc.)

Full debug detail:
`Traceback (most recent call last):
  File "/usr/local/bin/aws-google-auth", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/aws_google_auth/__init__.py", line 225, in main
    cli(cli_args)
  File "/usr/local/lib/python2.7/site-packages/aws_google_auth/__init__.py", line 64, in cli
    process_auth(args, config)
  File "/usr/local/lib/python2.7/site-packages/aws_google_auth/__init__.py", line 182, in process_auth
    config.raise_if_invalid()
  File "/usr/local/lib/python2.7/site-packages/aws_google_auth/configuration.py", line 117, in raise_if_invalid
    assert (self.password.__class__ is str), "Expected password to be a string. Got {}.".format(self.password.__class__)
AssertionError: Expected password to be a string. Got <type 'unicode'>.`

**Comment by sinkr** [comment]
Resolved by upgrading to Python 3.7.

**Comment by stevemac007** [comment]
I started work on this fix for 2.7 in `fix-keystore-unicode-password`.

**Comment by stevemac007** [comment]
Looks like that branch just needed some persuasion to fix the problem.
